name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        sudo apt-get update
        sudo apt-get install libigraph-dev
        sudo apt-get install libplot-dev
        sudo apt-get install libgeos-dev
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: make install
    - name: make test-install
      run: |
        find /usr/local -name "*wkt*" -print
        test -f /usr/local/include/wkt.h
        test -f /usr/local/bin/wktplot
        test -L /usr/local/lib/libwkt.so
        test -f /usr/local/lib/libwkt-0.1.so
        test -f /usr/local/lib/libwkt.a
    - name: make uninstall
      run: make uninstall
    - name: make test-uninstall
      run: |
        find /usr/local -name "*wkt*"  -print
        test \! -f /usr/local/include/wkt.h
        test \! -f /usr/local/bin/wktplot
        test \! -L /usr/local/lib/libwkt.so
        test \! -f /usr/local/lib/libwkt-0.1.so
        test \! -f /usr/local/lib/libwkt.a
